// <auto-generated />
using System;
using CleanArchCQRSMediatorAPI.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CleanArchCQRSMediatorAPI.Persistence.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20240823102506_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CleanArchCQRSMediatorAPI.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("BookCategory")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BorrowedMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("PublicationYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("BorrowedMemberId");

                    b.ToTable("Book", (string)null);
                });

            modelBuilder.Entity("CleanArchCQRSMediatorAPI.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<int>("MemberType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Member", (string)null);

                    b.HasDiscriminator().HasValue("Member");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CleanArchCQRSMediatorAPI.Domain.Entities.LibraryMember", b =>
                {
                    b.HasBaseType("CleanArchCQRSMediatorAPI.Domain.Entities.Member");

                    b.ToTable("Member", (string)null);

                    b.HasDiscriminator().HasValue("LibraryMember");
                });

            modelBuilder.Entity("CleanArchCQRSMediatorAPI.Domain.Entities.StaffMember", b =>
                {
                    b.HasBaseType("CleanArchCQRSMediatorAPI.Domain.Entities.Member");

                    b.Property<int>("StaffType")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("StaffMember");
                });

            modelBuilder.Entity("CleanArchCQRSMediatorAPI.Domain.Entities.Book", b =>
                {
                    b.HasOne("CleanArchCQRSMediatorAPI.Domain.Entities.LibraryMember", "BorrowedMember")
                        .WithMany("BorrowedBooks")
                        .HasForeignKey("BorrowedMemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("BorrowedMember");
                });

            modelBuilder.Entity("CleanArchCQRSMediatorAPI.Domain.Entities.LibraryMember", b =>
                {
                    b.Navigation("BorrowedBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
